name: Pytest (junit)
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: actions/setup-node@v4

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    # Run your automated tests & generate a report file
    - name: Tests
      run: |
          pytest --junitxml=results/report.xml

    # Run CLI to upload results
    - name: Upload test results to Testiny
      if: ${{ !cancelled() }}
      env: 
        TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
      run: |
        npm install --no-save @testiny/cli@latest
        npx @testiny/cli automation --project 57 --source pytest --junit results/report.xml --custom-result-fields=type